


MODULE_LIBS =   \
          ./libs/Work.o \
          ./libs/OutsideNet.o \
          ./libs/main.o \
          ./libs/GateUser.o \
          ./libs/Config.o \



MODULE_SRC =     \
          ./Work.o \
          ./OutsideNet.o \
          ./main.o \
          ./GateUser.o \
          ./Config.o \
